### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by Inferior-Gentleman** [xuanyuan14/CACM-master#1]
Can you give some examples about how to use node2vec to get embeddings and how to map queries ,documents into node identifiers?

And I can't access the dataset through your link http://www.thuir.cn/tiangong-st/

**Comment by xuanyuan14** [comment]
First, thank you for your question! 
About how to get node embeddings, you should  first build a query-document graph on your session dataset (details of how to build this graph and how to assign weights for each edge can be found in the published paper of CACM). 
Then given this graph file (the format of each line is nodeid1 nodeid2 weight), you can use the tools in https://github.com/snap-stanford/snap/tree/master/examples/node2vec to obtain the embedding for each node.

About the dataset, you cannot directly download the dataset through the link http://www.thuir.cn/tiangong-st/. This cite is only an introduction page of the TianGong-ST dataset. If you want to obtain the dataset, please communicate with the liaison (frankyzf94@gmail.com) given in that page. He will then reply to you of how to get the dataset.

**Comment by Inferior-Gentleman** [comment]
Thank you , I'll try it

**Comment by Inferior-Gentleman** [comment]
I 've read the paper of CACM, there are some questions:
(1) what's the difference between the defination of "user interaction" and "session"
(2) what's the meaning of examination probability ? why should we add the specific module to predict it? 
(3) using graph to get the embedding of query/doc is better than using pre-trained model like word2vec/BERT or something?

**Comment by xuanyuan14** [comment]
Answer:
1) One search session includes several queries, there may be some user interactive behaviors on these queries. Therefore, a session may contain several user interactions.
2) The examination probability means how many chances will a user read a search result. This is a term in click model. If you still cannot follow me, please first refer to related papers to understand what is click model. Here is a recommendation: Aleksandr Chuklin, Ilya Markov, and Maarten de Rijke. 2015. Click models for web search. Synthesis Lectures on Information Concepts, Retrieval, and Services 7, 3 (2015), 1–115.

There are explanations in the paper that we build our model according to the examination hypothesis. So we add a specific module to predict it because we would like to make our model with higher interpretability. 

3) This is uncertain, because comparing the graph embeddings with BERT is like comparing apple with banana.  Word2vec/BERT create content-based embeddings. However, node2vec is graph-based. They have their own advantages and limitations. Therefore, there is no comparability.

All in all, thank you for questions. Whereas, I would suggest you to ask more about the code itself on this github platform. Details about the paper can be discussed privately. You can contact the emails given in the paper.

**Comment by Inferior-Gentleman** [comment]
Thank you for replying, I 'm new to this field so there are much things to learn. I will be more cautious next time : )
